let lessons = [
  {
    id: 1,
    subject: "Arduino",
    location: "Dubai, UAE",
    price: 2000,
    spaces: 5,
    displaySpaces: 5,
    rating: 5,
    image: "./img/arduino.jpg",
  },
  {
    id: 2,
    subject: "Python",
    location: "Mumbai, India",
    price: 1000,
    spaces: 5,
    displaySpaces: 5,
    rating: 5,
    image: "./img/python.jpg",
  },
  {
    id: 3,
    subject: "JavaScript",
    location: "London, UK",
    price: 1500,
    spaces: 5,
    displaySpaces: 5,
    rating: 4.5,
    image: "./img/js.jpg",
  },
  {
    id: 4,
    subject: "Vue",
    location: "Dubai, UAE",
    price: 1000,
    spaces: 5,
    displaySpaces: 5,
    rating: 4,
    image: "./img/vue.jpg",
  },
  {
    id: 5,
    subject: "React",
    location: "Colarado, USA",
    price: 1200,
    spaces: 5,
    displaySpaces: 5,
    rating: 4.5,
    image: "./img/react.jpg",
  },
  {
    id: 6,
    subject: "MySQL",
    location: "Dubai, UAE",
    price: 800,
    spaces: 5,
    displaySpaces: 5,
    rating: 3,
    image: "./img/sql.jpg",
  },
];
