let lessons = [
  {
    id: 1,
    subject: "Arduino",
    location: "Dubai, UAE",
    price: 2000,
    spaces: 5,
    displaySpaces: 5,
    image: "./img/arduino.jpg",
  },
  {
    id: 2,
    subject: "Literature",
    location: "Mumbai, India",
    price: 1000,
    spaces: 5,
    displaySpaces: 5,
    image: "./img/literature.png",
  },
  {
    id: 3,
    subject: "Swimming",
    location: "London, UK",
    price: 1500,
    spaces: 5,
    displaySpaces: 5,
    image: "./img/swimming.png",
  },
  {
    id: 4,
    subject: "Music",
    location: "Dubai, UAE",
    price: 1000,
    spaces: 5,
    displaySpaces: 5,
    image: "./img/music.png",
  },
  {
    id: 5,
    subject: "Dance",
    location: "Colarado, USA",
    price: 1200,
    spaces: 5,
    displaySpaces: 5,
    image: "./img/dance.png",
  },
  {
    id: 6,
    subject: "Math",
    location: "Dubai, UAE",
    price: 800,
    spaces: 5,
    displaySpaces: 5,
    image: "./img/math.png",
  },
  {
    id: 7,
    subject: "Database",
    location: "Dubai, UAE",
    price: 900,
    spaces: 5,
    displaySpaces: 5,
    image: "./img/nosql.png",
  },
  {
    id: 8,
    subject: "Football",
    location: "Dubai, UAE",
    price: 1100,
    spaces: 5,
    displaySpaces: 5,
    image: "./img/fb.png",
  },
  {
    id: 9,
    subject: "Games",
    location: "Dubai, UAE",
    price: 1000,
    spaces: 5,
    displaySpaces: 5,
    image: "./img/game.png",
  },
  {
    id: 10,
    subject: "Coding",
    location: "Dubai, UAE",
    price: 1700,
    spaces: 5,
    displaySpaces: 5,
    image: "./img/vue.png",
  },
  {
    id: 11,
    subject: "Coding abc",
    location: "Dubai, UAE",
    price: 1700,
    spaces: 5,
    displaySpaces: 5,
    image: "./img/vue.png",
  },
];
