let lessons = [
  {
    id: 1,
    subject: "Arduino",
    location: "Dubai, UAE",
    price: 2000,
    spaces: 6,
    rating: 5,
  },
  {
    id: 2,
    subject: "Python",
    location: "Mumbai, India",
    price: 1000,
    spaces: 10,
    rating: 5,
  },
  {
    id: 3,
    subject: "JavaScript",
    location: "London, UK",
    price: 1500,
    spaces: 15,
    rating: 4.5,
  },
  {
    id: 4,
    subject: "Vue",
    location: "Dubai, UAE",
    price: 1000,
    spaces: 11,
    rating: 4,
  },
  {
    id: 5,
    subject: "Node",
    location: "Colarado, USA",
    price: 1200,
    spaces: 19,
    rating: 4.5,
  },
  {
    id: 6,
    subject: "MongoDB",
    location: "Dubai, UAE",
    price: 800,
    spaces: 10,
    rating: 3,
  },
];
